// Code generated by mockery v2.53.2. DO NOT EDIT.

package shim

import (
	queryresult "github.com/hyperledger/fabric-protos-go-apiv2/ledger/queryresult"
	mock "github.com/stretchr/testify/mock"
)

// MockStateQueryIteratorInterface is an autogenerated mock type for the StateQueryIteratorInterface type
type MockStateQueryIteratorInterface struct {
	mock.Mock
}

type MockStateQueryIteratorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateQueryIteratorInterface) EXPECT() *MockStateQueryIteratorInterface_Expecter {
	return &MockStateQueryIteratorInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockStateQueryIteratorInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStateQueryIteratorInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStateQueryIteratorInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStateQueryIteratorInterface_Expecter) Close() *MockStateQueryIteratorInterface_Close_Call {
	return &MockStateQueryIteratorInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStateQueryIteratorInterface_Close_Call) Run(run func()) *MockStateQueryIteratorInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateQueryIteratorInterface_Close_Call) Return(_a0 error) *MockStateQueryIteratorInterface_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStateQueryIteratorInterface_Close_Call) RunAndReturn(run func() error) *MockStateQueryIteratorInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// HasNext provides a mock function with no fields
func (_m *MockStateQueryIteratorInterface) HasNext() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNext")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockStateQueryIteratorInterface_HasNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNext'
type MockStateQueryIteratorInterface_HasNext_Call struct {
	*mock.Call
}

// HasNext is a helper method to define mock.On call
func (_e *MockStateQueryIteratorInterface_Expecter) HasNext() *MockStateQueryIteratorInterface_HasNext_Call {
	return &MockStateQueryIteratorInterface_HasNext_Call{Call: _e.mock.On("HasNext")}
}

func (_c *MockStateQueryIteratorInterface_HasNext_Call) Run(run func()) *MockStateQueryIteratorInterface_HasNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateQueryIteratorInterface_HasNext_Call) Return(_a0 bool) *MockStateQueryIteratorInterface_HasNext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStateQueryIteratorInterface_HasNext_Call) RunAndReturn(run func() bool) *MockStateQueryIteratorInterface_HasNext_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with no fields
func (_m *MockStateQueryIteratorInterface) Next() (*queryresult.KV, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *queryresult.KV
	var r1 error
	if rf, ok := ret.Get(0).(func() (*queryresult.KV, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *queryresult.KV); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queryresult.KV)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStateQueryIteratorInterface_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockStateQueryIteratorInterface_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockStateQueryIteratorInterface_Expecter) Next() *MockStateQueryIteratorInterface_Next_Call {
	return &MockStateQueryIteratorInterface_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockStateQueryIteratorInterface_Next_Call) Run(run func()) *MockStateQueryIteratorInterface_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStateQueryIteratorInterface_Next_Call) Return(_a0 *queryresult.KV, _a1 error) *MockStateQueryIteratorInterface_Next_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStateQueryIteratorInterface_Next_Call) RunAndReturn(run func() (*queryresult.KV, error)) *MockStateQueryIteratorInterface_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateQueryIteratorInterface creates a new instance of MockStateQueryIteratorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateQueryIteratorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateQueryIteratorInterface {
	mock := &MockStateQueryIteratorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
