// Code generated by mockery v2.53.2. DO NOT EDIT.

package shim

import (
	queryresult "github.com/hyperledger/fabric-protos-go-apiv2/ledger/queryresult"
	mock "github.com/stretchr/testify/mock"
)

// MockHistoryQueryIteratorInterface is an autogenerated mock type for the HistoryQueryIteratorInterface type
type MockHistoryQueryIteratorInterface struct {
	mock.Mock
}

type MockHistoryQueryIteratorInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHistoryQueryIteratorInterface) EXPECT() *MockHistoryQueryIteratorInterface_Expecter {
	return &MockHistoryQueryIteratorInterface_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockHistoryQueryIteratorInterface) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHistoryQueryIteratorInterface_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockHistoryQueryIteratorInterface_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockHistoryQueryIteratorInterface_Expecter) Close() *MockHistoryQueryIteratorInterface_Close_Call {
	return &MockHistoryQueryIteratorInterface_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockHistoryQueryIteratorInterface_Close_Call) Run(run func()) *MockHistoryQueryIteratorInterface_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHistoryQueryIteratorInterface_Close_Call) Return(_a0 error) *MockHistoryQueryIteratorInterface_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHistoryQueryIteratorInterface_Close_Call) RunAndReturn(run func() error) *MockHistoryQueryIteratorInterface_Close_Call {
	_c.Call.Return(run)
	return _c
}

// HasNext provides a mock function with no fields
func (_m *MockHistoryQueryIteratorInterface) HasNext() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HasNext")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockHistoryQueryIteratorInterface_HasNext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasNext'
type MockHistoryQueryIteratorInterface_HasNext_Call struct {
	*mock.Call
}

// HasNext is a helper method to define mock.On call
func (_e *MockHistoryQueryIteratorInterface_Expecter) HasNext() *MockHistoryQueryIteratorInterface_HasNext_Call {
	return &MockHistoryQueryIteratorInterface_HasNext_Call{Call: _e.mock.On("HasNext")}
}

func (_c *MockHistoryQueryIteratorInterface_HasNext_Call) Run(run func()) *MockHistoryQueryIteratorInterface_HasNext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHistoryQueryIteratorInterface_HasNext_Call) Return(_a0 bool) *MockHistoryQueryIteratorInterface_HasNext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHistoryQueryIteratorInterface_HasNext_Call) RunAndReturn(run func() bool) *MockHistoryQueryIteratorInterface_HasNext_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with no fields
func (_m *MockHistoryQueryIteratorInterface) Next() (*queryresult.KeyModification, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *queryresult.KeyModification
	var r1 error
	if rf, ok := ret.Get(0).(func() (*queryresult.KeyModification, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *queryresult.KeyModification); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*queryresult.KeyModification)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHistoryQueryIteratorInterface_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockHistoryQueryIteratorInterface_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockHistoryQueryIteratorInterface_Expecter) Next() *MockHistoryQueryIteratorInterface_Next_Call {
	return &MockHistoryQueryIteratorInterface_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockHistoryQueryIteratorInterface_Next_Call) Run(run func()) *MockHistoryQueryIteratorInterface_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHistoryQueryIteratorInterface_Next_Call) Return(_a0 *queryresult.KeyModification, _a1 error) *MockHistoryQueryIteratorInterface_Next_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHistoryQueryIteratorInterface_Next_Call) RunAndReturn(run func() (*queryresult.KeyModification, error)) *MockHistoryQueryIteratorInterface_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHistoryQueryIteratorInterface creates a new instance of MockHistoryQueryIteratorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHistoryQueryIteratorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHistoryQueryIteratorInterface {
	mock := &MockHistoryQueryIteratorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
