// Code generated by mockery v2.53.2. DO NOT EDIT.

package contractapi

import (
	cid "github.com/hyperledger/fabric-chaincode-go/v2/pkg/cid"

	mock "github.com/stretchr/testify/mock"

	shim "github.com/hyperledger/fabric-chaincode-go/v2/shim"
)

// MockTransactionContextInterface is an autogenerated mock type for the TransactionContextInterface type
type MockTransactionContextInterface struct {
	mock.Mock
}

type MockTransactionContextInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionContextInterface) EXPECT() *MockTransactionContextInterface_Expecter {
	return &MockTransactionContextInterface_Expecter{mock: &_m.Mock}
}

// GetClientIdentity provides a mock function with no fields
func (_m *MockTransactionContextInterface) GetClientIdentity() cid.ClientIdentity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClientIdentity")
	}

	var r0 cid.ClientIdentity
	if rf, ok := ret.Get(0).(func() cid.ClientIdentity); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cid.ClientIdentity)
		}
	}

	return r0
}

// MockTransactionContextInterface_GetClientIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientIdentity'
type MockTransactionContextInterface_GetClientIdentity_Call struct {
	*mock.Call
}

// GetClientIdentity is a helper method to define mock.On call
func (_e *MockTransactionContextInterface_Expecter) GetClientIdentity() *MockTransactionContextInterface_GetClientIdentity_Call {
	return &MockTransactionContextInterface_GetClientIdentity_Call{Call: _e.mock.On("GetClientIdentity")}
}

func (_c *MockTransactionContextInterface_GetClientIdentity_Call) Run(run func()) *MockTransactionContextInterface_GetClientIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionContextInterface_GetClientIdentity_Call) Return(_a0 cid.ClientIdentity) *MockTransactionContextInterface_GetClientIdentity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionContextInterface_GetClientIdentity_Call) RunAndReturn(run func() cid.ClientIdentity) *MockTransactionContextInterface_GetClientIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// GetStub provides a mock function with no fields
func (_m *MockTransactionContextInterface) GetStub() shim.ChaincodeStubInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStub")
	}

	var r0 shim.ChaincodeStubInterface
	if rf, ok := ret.Get(0).(func() shim.ChaincodeStubInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(shim.ChaincodeStubInterface)
		}
	}

	return r0
}

// MockTransactionContextInterface_GetStub_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStub'
type MockTransactionContextInterface_GetStub_Call struct {
	*mock.Call
}

// GetStub is a helper method to define mock.On call
func (_e *MockTransactionContextInterface_Expecter) GetStub() *MockTransactionContextInterface_GetStub_Call {
	return &MockTransactionContextInterface_GetStub_Call{Call: _e.mock.On("GetStub")}
}

func (_c *MockTransactionContextInterface_GetStub_Call) Run(run func()) *MockTransactionContextInterface_GetStub_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionContextInterface_GetStub_Call) Return(_a0 shim.ChaincodeStubInterface) *MockTransactionContextInterface_GetStub_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionContextInterface_GetStub_Call) RunAndReturn(run func() shim.ChaincodeStubInterface) *MockTransactionContextInterface_GetStub_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionContextInterface creates a new instance of MockTransactionContextInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionContextInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionContextInterface {
	mock := &MockTransactionContextInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
