# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: classicschain.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Owners
  # ---------------------------------------------------------------------------
  - Name: Owners
    Domain: owners.classicschain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Workshops
  # ---------------------------------------------------------------------------
  - Name: Workshops
    Domain: workshops.classicschain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Certifiers
  # ---------------------------------------------------------------------------
  - Name: Certifiers
    Domain: certifiers.classicschain.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1