// Code generated by mockery v2.53.2. DO NOT EDIT.

package cid

import (
	x509 "crypto/x509"

	mock "github.com/stretchr/testify/mock"
)

// MockClientIdentity is an autogenerated mock type for the ClientIdentity type
type MockClientIdentity struct {
	mock.Mock
}

type MockClientIdentity_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientIdentity) EXPECT() *MockClientIdentity_Expecter {
	return &MockClientIdentity_Expecter{mock: &_m.Mock}
}

// AssertAttributeValue provides a mock function with given fields: attrName, attrValue
func (_m *MockClientIdentity) AssertAttributeValue(attrName string, attrValue string) error {
	ret := _m.Called(attrName, attrValue)

	if len(ret) == 0 {
		panic("no return value specified for AssertAttributeValue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(attrName, attrValue)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClientIdentity_AssertAttributeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertAttributeValue'
type MockClientIdentity_AssertAttributeValue_Call struct {
	*mock.Call
}

// AssertAttributeValue is a helper method to define mock.On call
//   - attrName string
//   - attrValue string
func (_e *MockClientIdentity_Expecter) AssertAttributeValue(attrName interface{}, attrValue interface{}) *MockClientIdentity_AssertAttributeValue_Call {
	return &MockClientIdentity_AssertAttributeValue_Call{Call: _e.mock.On("AssertAttributeValue", attrName, attrValue)}
}

func (_c *MockClientIdentity_AssertAttributeValue_Call) Run(run func(attrName string, attrValue string)) *MockClientIdentity_AssertAttributeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockClientIdentity_AssertAttributeValue_Call) Return(_a0 error) *MockClientIdentity_AssertAttributeValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClientIdentity_AssertAttributeValue_Call) RunAndReturn(run func(string, string) error) *MockClientIdentity_AssertAttributeValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttributeValue provides a mock function with given fields: attrName
func (_m *MockClientIdentity) GetAttributeValue(attrName string) (string, bool, error) {
	ret := _m.Called(attrName)

	if len(ret) == 0 {
		panic("no return value specified for GetAttributeValue")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, bool, error)); ok {
		return rf(attrName)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(attrName)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(attrName)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(attrName)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockClientIdentity_GetAttributeValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttributeValue'
type MockClientIdentity_GetAttributeValue_Call struct {
	*mock.Call
}

// GetAttributeValue is a helper method to define mock.On call
//   - attrName string
func (_e *MockClientIdentity_Expecter) GetAttributeValue(attrName interface{}) *MockClientIdentity_GetAttributeValue_Call {
	return &MockClientIdentity_GetAttributeValue_Call{Call: _e.mock.On("GetAttributeValue", attrName)}
}

func (_c *MockClientIdentity_GetAttributeValue_Call) Run(run func(attrName string)) *MockClientIdentity_GetAttributeValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClientIdentity_GetAttributeValue_Call) Return(value string, found bool, err error) *MockClientIdentity_GetAttributeValue_Call {
	_c.Call.Return(value, found, err)
	return _c
}

func (_c *MockClientIdentity_GetAttributeValue_Call) RunAndReturn(run func(string) (string, bool, error)) *MockClientIdentity_GetAttributeValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetID provides a mock function with no fields
func (_m *MockClientIdentity) GetID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientIdentity_GetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetID'
type MockClientIdentity_GetID_Call struct {
	*mock.Call
}

// GetID is a helper method to define mock.On call
func (_e *MockClientIdentity_Expecter) GetID() *MockClientIdentity_GetID_Call {
	return &MockClientIdentity_GetID_Call{Call: _e.mock.On("GetID")}
}

func (_c *MockClientIdentity_GetID_Call) Run(run func()) *MockClientIdentity_GetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientIdentity_GetID_Call) Return(_a0 string, _a1 error) *MockClientIdentity_GetID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientIdentity_GetID_Call) RunAndReturn(run func() (string, error)) *MockClientIdentity_GetID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMSPID provides a mock function with no fields
func (_m *MockClientIdentity) GetMSPID() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMSPID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientIdentity_GetMSPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMSPID'
type MockClientIdentity_GetMSPID_Call struct {
	*mock.Call
}

// GetMSPID is a helper method to define mock.On call
func (_e *MockClientIdentity_Expecter) GetMSPID() *MockClientIdentity_GetMSPID_Call {
	return &MockClientIdentity_GetMSPID_Call{Call: _e.mock.On("GetMSPID")}
}

func (_c *MockClientIdentity_GetMSPID_Call) Run(run func()) *MockClientIdentity_GetMSPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientIdentity_GetMSPID_Call) Return(_a0 string, _a1 error) *MockClientIdentity_GetMSPID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientIdentity_GetMSPID_Call) RunAndReturn(run func() (string, error)) *MockClientIdentity_GetMSPID_Call {
	_c.Call.Return(run)
	return _c
}

// GetX509Certificate provides a mock function with no fields
func (_m *MockClientIdentity) GetX509Certificate() (*x509.Certificate, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetX509Certificate")
	}

	var r0 *x509.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func() (*x509.Certificate, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *x509.Certificate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*x509.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClientIdentity_GetX509Certificate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetX509Certificate'
type MockClientIdentity_GetX509Certificate_Call struct {
	*mock.Call
}

// GetX509Certificate is a helper method to define mock.On call
func (_e *MockClientIdentity_Expecter) GetX509Certificate() *MockClientIdentity_GetX509Certificate_Call {
	return &MockClientIdentity_GetX509Certificate_Call{Call: _e.mock.On("GetX509Certificate")}
}

func (_c *MockClientIdentity_GetX509Certificate_Call) Run(run func()) *MockClientIdentity_GetX509Certificate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClientIdentity_GetX509Certificate_Call) Return(_a0 *x509.Certificate, _a1 error) *MockClientIdentity_GetX509Certificate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClientIdentity_GetX509Certificate_Call) RunAndReturn(run func() (*x509.Certificate, error)) *MockClientIdentity_GetX509Certificate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClientIdentity creates a new instance of MockClientIdentity. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientIdentity(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientIdentity {
	mock := &MockClientIdentity{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
