with-expecter: true
packages:
  github.com/hyperledger/fabric-contract-api-go/v2/contractapi:
    interfaces:
      TransactionContextInterface:
  github.com/hyperledger/fabric-chaincode-go/v2/shim:
    interfaces:
      ChaincodeStubInterface:
      HistoryQueryIteratorInterface:
      StateQueryIteratorInterface:
  github.com/hyperledger/fabric-chaincode-go/v2/pkg/cid:
    interfaces:
      ClientIdentity: